config/routes.rb
Rails.application.routes.draw do
  resources :contacts
    root 'contacts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :company, :cellphone, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="">
  <%= form_with(model: contact, local: true) do |form| %>

  <div class="col-md-12">
    <% @contact.errors.full_messages.each do |message| %> <!--representacion de cadena de texto en palabras sobre errores-->
    <button type="button"  class="btn-danger error-btn"><%= message %></button>
    <!--mensaje de error-->
    <%end%>
  </div>

  <div class="field col-md-12">
    <div class="row">
      <br>
      <i class="fa fa-user  btn btn-danger  col-sm-1 center"></i>
      <div class="col-sm-11">
        <%= form.text_field :name , class: 'form-control form-control-lg', placeholder:"Name" %>
        <br>
      </div>
    </div>
  </div>

  <div class="field col-md-12 ">
    <div class="row">
      <i class="fa fa-building-o  btn btn-danger  col-sm-1 center" ></i>
      <div class="col-sm-11">
          <%= form.text_field :company, class: 'form-control form-control-lg', placeholder:"Company" %>
        <br>
      </div>
    </div>
  </div>
  <div class="field col-md-12 ">
    <div class="row">
      <i class="fa fa-mobile  btn btn-danger  col-sm-1 center" ></i>
      <div class="col-sm-11">
        <%= form.number_field :cellphone, class: 'form-control form-control-lg', placeholder:"Cellphone" %>
        <br>
      </div>
    </div>
  </div>

  <div class="field col-md-12">
    <div class="row">
      <i class="fa fa-phone  btn btn-danger  col-sm-1 center" ></i>
      <div class="col-sm-11">
        <%= form.number_field :phone, class: 'form-control form-control-lg', placeholder:"Phone" %>
        <br>
      </div>
    </div>
  </div>

  <div class="field col-md-12">
    <div class="row">
      <i class="fa fa-envelope  btn btn-danger  col-sm-1 center"></i>
      <div class="col-sm-11">
        <%= form.text_field :email, class: 'form-control form-control-lg', placeholder:"Email" %>
        <br>
      </div>
    </div>
  </div>

  <div class="actions col-12">

    <%= form.submit :Send, class: 'btn btn-danger btn-lg btn-block' %>
  </div>
  <% end %>

</div>

app/views/contacts/edit.html.erb
<div class="container mt-100" >
   <div class="card-header btn btn-danger col-md-12 ">
     <h1>Editing Contact</h1>
   </div>

  <div class="full-container">
    <br>
    <%= render 'form', contact: @contact %>

    <%= link_to  contacts_path,method: :get, class: " btn btn-danger  ", style:"padding:6px;" do %>
    <i class="fa fa-arrow-left col-sm-2 " style="color:white;"></i>
    <%end%>
  </div>

</div>

app/views/contacts/index.html.erb
  <div class="container ">
    <p id="notice"><%= notice %></p>
    <div class="container btn btn-danger col-md-12 ">
      <h1 class="text-center">Contact List</h1>

    </div>

        <% @contacts.each do |contact| %>
        <%= button_to contact_path(contact) ,method: :get, class:"container btn btn-default col-md-6", style:"height:200px;" do %>
          <div class="col-md-12">
            <div class="col-md-3 " >
              <%= image_tag('Contact_Icon.png', size: "100") %>
            </div>
            <div class="col-md-3 text-left mt-20" >
              <h4 class="font-merri"><%= contact.name %></h4>
              <p class="text-muted"><%= contact.company %></p>
            </div>
            <div class="col-md-6 row contact-list-btn" >
                <%= link_to edit_contact_path(contact),method: :get, class: " btn btn-success btn-padding mr-2" do %>
                  <i class="fa fa-pencil col-sm-2 fa-icons-color"></i>
                <%end%>
                <%= link_to (contact), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-padding" do %>
                  <i class="fa fa-close col-sm-2 fa-icons-color"></i>
                <%end%>
            </div>
          </div>
          <div class="col-md-12 ">
            <hr>
            <div class="col-md-4 row">
              <i class="fa fa-mobile col-sm-2 fa-padding" ></i>
              <p class="col-sm-8"><%= contact.cellphone %></p>
            </div>
            <div class="col-md-4">
              <i class="fa fa-phone col-sm-2 fa-padding "></i>
              <p class="col-sm-8"><%= contact.phone %></p>
            </div>
            <div class="col-md-4">
              <i class="fa fa-envelope col-sm-2 fa-padding"></i>
              <p class="col-sm-8"><%= contact.email %></p>
            </div>
          </div>
        <%end%>
      <% end %>
      <%= button_to new_contact_path,method: :get,class:"col-md-6 btn btn-default new-contact-btn" do%>
      <i class="fa fa-plus"></i>
      <% end %>
  </div>

app/views/contacts/new.html.erb
  <div class="container mt-100">
     <div class="card-header btn btn-danger col-md-12 ">
       <h1 class="">New Contact</h1>
     </div>

    <div class="full-container" >
      <br>
      <%= render 'form', contact: @contact %>

      <%= link_to  contacts_path,method: :get, class: " btn btn-danger  ", style:"padding:6px;" do %>
      <i class="fa fa-arrow-left col-sm-2 " style="color:white;"></i>
      <%end%>
    </div>

</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container btn-danger contact-full-info">
  <div class="col-md-8">
    <div class="col-md-3 ">
    <%= image_tag('user_contact.jpg', size: "90x100") %>
    </div>
    <div class="col-md-8 text-left " >
      <h1 style="margin-top:0px;font-family: 'Roboto Slab', serif;"><%= @contact.name %></h1>

      <h3 style="margin-top:0px;font-family: 'Playfair Display', serif;"><%= @contact.company %></h3>

    </div>
  </div>
  <div class="col-md-4 text-left"style="border-left: 1px solid ;">
    <p>
      <strong>Cellphone:</strong>
      <%= @contact.cellphone %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @contact.phone %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @contact.email %>
    </p>


  </div>
</div>
<div class="container btn btn-default justify-content-between row contact-full-info-btn">
  <%= link_to  contacts_path,method: :get, class: " btn btn-danger  ", style:"padding:6px;" do %>
  <i class="fa fa-arrow-left col-sm-2 " style="color:white;"></i>
  <%end%>
  <%= link_to edit_contact_path(@contact),method: :get, class: " btn btn-success  ", style:"padding:6px;margin-left:660px;" do %>
    <i class="fa fa-pencil col-sm-2 " style="color:white;"></i>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <title>Contactos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
  <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</html>